sonar.projectKey=deeprath_commerce-platform
sonar.organization=deeprath

sonar.sources=pkg,services,proto
sonar.tests=pkg,services
sonar.test.inclusions=**/*_test.go
sonar.exclusions=gen/**,**/*.pb.go,**/*_grpc.pb.go,**/mocks/**,deploy/**

sonar.go.coverage.reportPaths=coverage.out

sonar.sourceEncoding=UTF-8
