{{- range $name, $rawSvc := .Values.services }}
{{- $svc := mergeOverwrite (deepCopy $.Values.defaults) $rawSvc }}
{{- if $svc.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{- include "commerce.labels" (dict "name" $name "root" $) | nindent 4 }}
spec:
  minAvailable: {{ $svc.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "commerce.selectorLabels" (dict "name" $name) | nindent 6 }}
---
{{- end }}
{{- end }}
