spec:
  targetRevision: main # promote by updating this to a release tag
  syncPolicy:
    automated:
      prune: false   # prod prunes only on manual sync
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true

istio:
  profile: ambient
  meshConfig:
    # Sample 5% of traces in production.
    extensionProviders:
      - name: otel
        opentelemetry:
          service: otel-collector.observability.svc.cluster.local
          port: 4317
      - name: ext-authz-grpc
        envoyExtAuthzGrpc:
          service: ext-authz.commerce.svc.cluster.local
          port: 50051
      - name: edge-ratelimit
        envoyRateLimit:
          service: ratelimit.commerce.svc.cluster.local
          port: 8081
